### PR TITLE
fix: removed firefox icon

### LINKED ISSUE #1710: 🐛 BUG: Firefox Icon in Get Started With Squads
### What went wrong? 🤔

When you join a squad, the Get Started checklist "download the browser extension" section presents the Firefox icon, even though it is not supported (for reasons in #1320).

### Expected Behavior

Only the supported icons are shown

### Steps to Reproduce Issue

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See the error
```

### Solution Proposed

Remove the Firefox icon

### Screenshots

 Image

### Environment

_No response_

### Browsers

Firefox, Chrome

### OS

Linux

### Version of daily.dev

_No response_

### Additional Context

```bash

```

### Code of Conduct

- [x] I follow the conditions of this project.

### PR DESCRIPTION
**Pull request by giuszeppe**
## Changes
I removed the Firefox icon since it is not supported.
Closes [#1710](https://github.com/dailydotdev/daily/issues/1710)

### CODE REVIEW

**Comment by sshanzel** [comment]
Hi @giuszeppe. Kindly refer to Amar's comment, then I think we can delete the modified SVG file here. Thank you!

File: packages/shared/src/components/checklist/InstallExtensionChecklistStep.tsx [hunk 1]
```diff
@@ -3,7 +3,7 @@ import React from 'react';
 import type { ChecklistStepProps } from '../../lib/checklist';
 import { ChecklistStep } from './ChecklistStep';
 import { Button, ButtonVariant } from '../buttons/Button';
-import BrowsersIcon from '../../../icons/browsers.svg';
+import BrowsersIcon from '../icons/Browsers/group.svg';
```
Comment (sshanzel) [inline packages/shared/src/components/checklist/InstallExtensionChecklistStep.tsx:6]: I see that you are now using the correct SVG. We can now just delete the modified file above.

**Review by rebelchris — APPROVED** [review]

**Review by AmarTrebinjac — APPROVED** [review]

**Comment by sshanzel** [comment]
@giuszeppe thank you for your contribution! 🙌
